TV_POWER = "IR1/TV/POWER"
TV_POWER_STATE = "IR1/TV/POWER/STATE"

ANDROID_POWER = "IR1/ANDROID/POWER"
ANDROID_POWER_STATE = "IR1/ANDROID/POWER/STATE"

XBOX_POWER = "IR1/XBOX/POWER"
XBOX_POWER_STATE = "IR1/XBOX/POWER/STATE"
